import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { config } from 'dotenv';
config();

import { DatabaseService } from './database.service';
import {
  ProductEntity,
  ProductImageEntity,
  SupplierEntity,
  RoleEntity,
  PermissionEntity,
  StoreEntity,
  UserEntity,
  ReviewEntity,
  PromotionEntity,
  ProductPromotionEntity,
  VoucherEntity,
  VoucherCustomerEntity,
  CustomerEntity,
  OrderEntity,
  OrderItemEntity,
  InventoryEntity,
  InventoryDetailEntity,
  NewsEntity,
  CartItemEntity,
  CategoryEntity,
  PaymentTransactionEntity,
  ImportProductEntity,
  ImportProductDetailEntity,
  MessageEntity,
  ConversationEntity,
  OrderStatusHistoryEntity,
  DeliveryProofEntity,
  DriverLocationEntity,
  ProductClassificationEntity,
  ProductAttributeEntity,
  ClassificationAttributeRelationshipEntity,
  ImportRequestDetailEntity,
  ImportRequestEntity,
} from './entities';
import {
  ProductRepository,
  ProductImageRepository,
  SupplierRepository,
  RoleRepository,
  PermissionRepository,
  StoreRepository,
  UserRepository,
  ReviewRepository,
  PromotionRepository,
  ProductPromotionRepository,
  VoucherRepository,
  VoucherCustomerRepository,
  CustomerRepository,
  OrderRepository,
  InventoryRepository,
  InventoryDetailRepository,
  NewsRepository,
  CartItemRepository,
  CategoryRepository,
  PaymentTransactionRepository,
  ImportProductRepository,
  ImportProductDetailRepository,
  OrderStatusHistoryRepository,
  DeliveryProofRepository,
  DriverLocationRepository,
  ProductClassificationRepository,
  ProductAttributeRepository,
  ClassificationAttributeRelationshipRepository,
  ImportRequestRepository,
  ImportRequestDetailRepository,
} from './repositories';

const postgresRepositories = [
  ProductRepository,
  ProductImageRepository,
  SupplierRepository,
  RoleRepository,
  PermissionRepository,
  StoreRepository,
  UserRepository,
  ReviewRepository,
  PromotionRepository,
  ProductPromotionRepository,
  VoucherRepository,
  VoucherCustomerRepository,
  CustomerRepository,
  OrderRepository,
  InventoryRepository,
  InventoryDetailRepository,
  NewsRepository,
  CartItemRepository,
  CategoryRepository,
  PaymentTransactionRepository,
  ImportProductRepository,
  ImportProductDetailRepository,
  OrderStatusHistoryRepository,
  DeliveryProofRepository,
  DriverLocationRepository,
  ProductClassificationRepository,
  ProductAttributeRepository,
  ClassificationAttributeRelationshipRepository,
  ImportRequestRepository,
  ImportRequestDetailRepository,
];
const postgresEntities = [
  ProductEntity,
  ProductImageEntity,
  SupplierEntity,
  RoleEntity,
  PermissionEntity,
  StoreEntity,
  UserEntity,
  ReviewEntity,
  PromotionEntity,
  ProductPromotionEntity,
  VoucherEntity,
  VoucherCustomerEntity,
  CustomerEntity,
  OrderEntity,
  OrderItemEntity,
  InventoryEntity,
  InventoryDetailEntity,
  NewsEntity,
  CartItemEntity,
  CategoryEntity,
  PaymentTransactionEntity,
  ImportProductEntity,
  ImportProductDetailEntity,
  MessageEntity,
  ConversationEntity,
  OrderStatusHistoryEntity,
  DeliveryProofEntity,
  DriverLocationEntity,
  ProductClassificationEntity,
  ProductAttributeEntity,
  ClassificationAttributeRelationshipEntity,
  ImportRequestEntity,
  ImportRequestDetailEntity,
];
@Module({
  imports: [
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: process.env.DB_HOST,
      port: Number(process.env.DB_PORT),
      username: process.env.DB_USERNAME,
      password: process.env.DB_PASSWORD,
      database: process.env.DB_DATABASE,
      entities: postgresEntities,
      schema: 'public',
      synchronize: process.env.NODE_ENV !== 'production',
      logging: process.env.NODE_ENV === 'development',
      ssl:
        process.env.NODE_ENV === 'production'
          ? { rejectUnauthorized: false }
          : false,
    }),
    TypeOrmModule.forFeature(postgresEntities),
  ],
  providers: [DatabaseService, ...postgresRepositories],
  exports: [DatabaseService, TypeOrmModule, ...postgresRepositories],
})
export class DatabaseModule { }
